/**
 * Default Learning Pathway categories seeded into the platform.
 * Each category maps to a set of symptom/topic names (subsections).
 * Superusers can edit these via Editorial Settings → Learning Pathway.
 */

export interface DefaultLearningCategory {
  id: string // slug used as stable seed key
  name: string
  slug: string
  ordering: number
  subsections: string[]
}

export const DEFAULT_LEARNING_CATEGORIES: DefaultLearningCategory[] = [
  {
    id: 'acute_emergency',
    slug: 'acute_emergency',
    name: 'Acute & Emergency Presentations',
    ordering: 1,
    subsections: [
      'Chest Pain',
      'Stroke',
      'Seizure',
      'Severe Headache',
      'Sudden Onset of Pain',
      'Sepsis',
      'Anaphylaxis',
      'Meningitis Rash',
      'Fainting',
      'Confusion',
      'High Fever',
      'Difficulty Breathing',
      'Breathing Problems / Shortness of Breath',
      'Rectal Bleeding / Blood in Stool',
      'Blood In The Urine For Men',
      'Blood In The Urine For Women',
      'Testicular Pain / Testicle Pain',
      'Safeguarding',
      'Needlestick Injury',
      'Post Surgical / Operation Complication',
    ],
  },
  {
    id: 'respiratory_ent',
    slug: 'respiratory_ent',
    name: 'Respiratory & ENT',
    ordering: 2,
    subsections: [
      'Asthma',
      'Coughs',
      'Cold / Flu',
      'Flu',
      'Covid',
      'Chest Infection',
      'Sore Throat',
      'Tonsillitis',
      'Sinusitis',
      'Laryngitis / Loss of Voice',
      'Ear Ache / Ear Infection',
      'Earache / Ear Infection',
      'Ear Wax',
      'Hearing Reduction (non wax)',
      'Nose Bleeds',
      'Snoring',
    ],
  },
  {
    id: 'skin_infections',
    slug: 'skin_infections',
    name: 'Skin, Rashes & Infections',
    ordering: 3,
    subsections: [
      'Rash',
      'Rash, spots and skin problems',
      'Eczema',
      'Psoriasis',
      'Acne',
      'Impetigo',
      'Cellulitis',
      'Boils',
      'Abcess',
      'Contact Dermatitis',
      'Ringworm',
      'Rosacea',
      'Fungal Nail Infection',
      "Athlete's Foot",
      'Head Lice',
      'Chicken Pox',
      'Shingles',
      'Scarlet Fever',
      'Slapped Cheek Syndrome',
      'Warts & Verrucae',
      'Sunburn',
    ],
  },
  {
    id: 'musculoskeletal_injury',
    slug: 'musculoskeletal_injury',
    name: 'Musculoskeletal & Injury',
    ordering: 4,
    subsections: [
      'Back Pain',
      'Neck Pain',
      'Shoulder Pain',
      'Hip Pain',
      'Knee Pain',
      'Ankle Pain',
      'Wrist Pain',
      'Hand Pain',
      'Foot Pain',
      "Elbow Pain (Including Golfer's Elbow or Tennis Elbow)",
      'Muscle Pain',
      'Sports Injury',
      'Sprain / Strain',
      'Whiplash',
      'Bunions',
      'Frozen Shoulder',
      'Gout',
    ],
  },
  {
    id: 'abdominal_digestive',
    slug: 'abdominal_digestive',
    name: 'Abdominal & Digestive',
    ordering: 5,
    subsections: [
      'Abdominal Pain',
      'Abdomen Pain',
      'Stomachache / Pain',
      'Indigestion',
      'Reflux',
      'Heartburn',
      'Irritable Bowel Syndrome (IBS)',
      'Bowel Problems / Constipation',
      'Constipation',
      'Diarrhoea & Vomiting',
      'Nausea and Vomiting',
      'Food Poisoning / Gastroenteritis',
      'Rectal Irritation',
      'Haemorrhoids / Piles',
    ],
  },
  {
    id: 'urinary_renal',
    slug: 'urinary_renal',
    name: 'Urinary & Renal',
    ordering: 6,
    subsections: [
      'Bladder infection  /Urinary Tract Infection (UTI) / Cystitis in women',
      'Bladder infection /Urinary Tract Infection (UTI) / Cystitis in Men',
      'Urine Infection (UTI)',
      'Difficulty Passing Urine / Urinary Retention',
      'Urinary Incontinence',
      'Kidney Pain',
      'Prostate / PSA',
    ],
  },
  {
    id: 'womens_health',
    slug: 'womens_health',
    name: "Women's Health & Pregnancy",
    ordering: 7,
    subsections: [
      'Pregnancy',
      'Morning sickness (pregnancy)',
      'Vaginal Bleeding',
      'Vaginal discharge',
      'Menstrual problem / Period problems',
      'Delay Period / Menstruation',
      'Menopause / HRT (Hormone Replacement Therapy)',
      'Contraception (Routine)',
      'Contraception (Emergency)',
      'Coil Implant / Removal',
      'Mastitis',
      'Postnatal Depression',
      'Fertility / Infertility',
      'Pregnancy Termination',
      'Prolapse',
    ],
  },
  {
    id: 'mens_genital',
    slug: 'mens_genital',
    name: "Men's & Genital Health",
    ordering: 8,
    subsections: [
      'Testicle / Testicular Lump',
      'Erection Difficulties',
      'Impotence',
      'Genital Herpes & Warts In Men & Women',
      'Spots on Genitals (Men & Women)',
      'Pubic Lice',
    ],
  },
  {
    id: 'mental_health',
    slug: 'mental_health',
    name: 'Mental Health & Neurodiversity',
    ordering: 9,
    subsections: [
      'Anxiety',
      'Depression / Low Mood',
      'Depression / Low Mood / Suicidal / Self-Harm',
      'Mental Health Concerns',
      'Stress',
      'Panic Attacks',
      'Psychological Issues',
      'Anorexia',
      'Binge Eating',
      'Difficulty Sleeping / Insomnia',
      'Dementia / Memory Loss',
      'Memory Loss',
      'ADHD / Autism',
      'Tics',
    ],
  },
  {
    id: 'long_term_conditions',
    slug: 'long_term_conditions',
    name: 'Long-Term Conditions & Chronic Disease',
    ordering: 10,
    subsections: [
      'Diabetic / Diabetes',
      'Diabetic Foot',
      'Blood Pressure (BP) (High Or Low)',
      'Cholesterol',
      'Epilepsy',
      'Chronic Fatigue Syndrome',
      'Obesity / Request for Weight Loss Injections',
      'Weight Issues',
      'Arthritis',
      'Varicose veins',
    ],
  },
  {
    id: 'eyes_mouth',
    slug: 'eyes_mouth',
    name: 'Eyes, Mouth & Dental',
    ordering: 11,
    subsections: [
      'Conjunctivitis / Sticky / Sore Eye',
      'Sticky / Sore eye / Conjunctivitis',
      'Styes',
      'Bloodshot Eye',
      'Eye Problems',
      'Mouth Ulcers',
      'Toothache',
    ],
  },
  {
    id: 'admin_process',
    slug: 'admin_process',
    name: 'Admin, Process & Other',
    ordering: 12,
    subsections: [
      'Fit Note',
      'Acute Medication Request',
      'Medication advice / side effects (except rash)',
      'Medication not available from pharmacy',
      'Hospital Discharge',
      'Chasing scan or test results requested by hospital',
      'DNACPR / TEP Form',
      'Patient Transport Request',
      'Travel Advice',
      'Professionals',
      'Telephone Fault / Issue',
      'Housebound / Home Visit request',
      'Random',
      'TestSymptom',
    ],
  },
]
